[package]
name      = "scaproust"
version   = "0.1.0"
authors   = ["blabaere <benoit.labaere@gmail.com>"]
readme    = "README.md"
keywords  = ["io", "nanomsg", "messaging"]
exclude   = [
  ".gitignore",
  ".travis.yml",
  "test/**/*",
]

[dependencies]
log = "0.3.3"
byteorder = "0.4.2"
time = "0.1.34"

[dependencies.mio]
git = "https://github.com/carllerche/mio"

#[dependencies.slab]
#git = "https://github.com/carllerche/slab"

[dev-dependencies]
env_logger = "0.3.2"

#[[test]]
#name = "test"
#path = "test/test.rs"
