[package]
name      = "scaproust"
version   = "0.1.0"
authors   = ["blabaere <benoit.labaere@gmail.com>"]
readme    = "README.md"
keywords  = ["io", "nanomsg", "messaging"]
exclude   = [
  ".gitignore",
  ".travis.yml",
  "test/**/*",
]

[dependencies]
log = "0.3.1"
byteorder = "0.3.10"
time = "0.1.30"

[dependencies.mio]
git = "https://github.com/carllerche/mio"

[dev-dependencies]
env_logger = "0.3.0"

[[test]]
name = "test"
path = "test/test.rs"
