[package]
name          = "scaproust"
version       = "0.1.0"
authors       = ["blabaere <benoit.labaere@gmail.com>"]
description   = "Nanomsg scalability protocols implementation in rust"
readme        = "README.md"
keywords      = ["io", "nanomsg", "messaging"]
license       = "MIT/Apache"
documentation = "https://blabaere.github.io/scaproust"
homepage      = "https://github.com/blabaere/scaproust"
repository    = "https://github.com/blabaere/scaproust"
exclude       = [
  ".gitignore",
  ".travis.yml",
  "appveyor.yml",
  "test/**/*",
]

[dependencies]
log = "0.3.6"
byteorder = "0.5.1"
time = "0.1.35"
clippy = "0.0.77"
#mio = "0.5.1"
mio = { git = "https://github.com/carllerche/mio", rev = "0a8089422d3bdf5ecb02593b4f68f25f8e985490" }

[dev-dependencies]
env_logger = "0.3.2"

[[test]]
name = "test"
path = "test/test.rs"
