[package]
name          = "scaproust"
version       = "0.1.0"
authors       = ["blabaere <benoit.labaere@gmail.com>"]
description   = "Nanomsg scalability protocols implementation in rust"
readme        = "README.md"
keywords      = ["io", "nanomsg", "messaging"]
license       = "MIT/Apache"
documentation = "https://blabaere.github.io/scaproust"
homepage      = "https://github.com/blabaere/scaproust"
repository    = "https://github.com/blabaere/scaproust"
exclude       = [
  ".gitignore",
  ".travis.yml",
  "appveyor.yml",
  "test/**/*",
]

[dependencies]
log = "0.3.3"
byteorder = "0.4.2"
time = "0.1.34"
#clippy = "0.0.56"

[dependencies.mio]
git = "https://github.com/carllerche/mio"

[dev-dependencies]
env_logger = "0.3.2"

[[test]]
name = "test"
path = "test/test.rs"
