[package]
name          = "scaproust"
version       = "0.1.0"
authors       = ["blabaere <benoit.labaere@gmail.com>"]
description   = "Nanomsg scalability protocols implementation in rust"
readme        = "README.md"
keywords      = ["io", "nanomsg", "messaging"]
license       = "MIT/Apache"
documentation = "https://blabaere.github.io/scaproust"
homepage      = "https://github.com/blabaere/scaproust"
repository    = "https://github.com/blabaere/scaproust"
exclude       = [
  ".gitignore",
  ".travis.yml",
  "appveyor.yml",
  "test/**/*",
]

[dependencies]
log = "0.3.6"
byteorder = "0.5.3"
time = "0.1.35"
clippy = "*"
#mio = "0.5.1"
#mio = { git = "https://github.com/carllerche/mio" }
mio = { git = "https://github.com/carllerche/mio", rev = "ce5d4fb5cde330c8486ddf3d91142ac03134c6d7" }

[dev-dependencies]
env_logger = "0.3.4"

[[test]]
name = "test"
path = "test/test.rs"
